@startuml sekwencyjny

actor Gość as user
boundary Formularz_logowania as gui
control MOKEndpoint as controller
control MOKService as service
control IdentityStore as auth



user -> gui ++ : Przekazanie danych do formularza
gui -> controller ++ : Przekazanie danych z formularza
controller -> service ++ : Przekazanie danych

group  Transaction.ReadCommited
service -> auth ++ : Przekazanie danych
auth -> service : Zwrócenie tokenu
end

service -> controller : Zwrócenie tokenu
controller --> gui : Zwrócenie tokenu
gui --> user : Przekierowanie na stronę uwierzytelnioną 

alt konto o podanych danych nie istnieje
    auth --> controller : HTTP 401
    controller --> gui : HTTP 401
    gui --> user : Komunikat o błędnie wprowadzonych danych 
end

@enduml