@startuml sekwencyjny

actor Gość as user
boundary Formularz_logowania as gui
control MOKEndpoint as controller
control MOKService as service
control IdentityStore as auth



user -> gui ++ : Przekazanie danych do formularza
gui -> controller ++ : Przekazanie danych z formularza
controller -> service ++ : Przekazanie danych



group  Transaction.ReadOnly
service -> auth ++ : Przekazanie danych
return : Zwrócenie statusu
end
alt konto o podanych danych istnieje
service --> controller : Zwrócenie tokenu
controller --> gui : Zwrócenie tokenu
gui --> user : Przekierowanie na stronę uwierzytelnioną 

else konto o podanych danych nie istnieje
    return HTTP 401
    return HTTP 401
    return Komunikat o błędnie wprowadzonych danych 
end


@enduml
