@startuml MOK.3 - Zablokuj konto

actor Administrator as admin
boundary AccountPanelPage as gui
control AccountEndpoint as controller
control AccountService as service
entity Account as account
control AccountFacade as facade



admin -> gui ++ : disableAccount(id)
gui -> controller ++ : disableAccount(id)
group Transaction.Never
    controller -> service ++ : disableAccount(id) 
    group Transaction.ReadCommitted
        service -> facade ++ : find(account)
        facade -> account : result
        service -> service : <<check>>
        service -> account : setActive(false)
        service -> facade : updateAccount(account)
        return success
    end
end

return success
return HTTP 200 OK
gui -> gui : <<render>>
return Informacja o zablokowaniu konta

alt użytkownik jest zablokowany
    admin -> gui ++ : disableAccount(id)
    gui -> controller ++ : disableAccount(id)
    controller -> service ++ : disableAccount(id) 
        service -> facade: find(account)
        facade -> account  : result
        service -> service : <<check>>
return fail
return HTTP 403 FORBIDDEN
gui -> gui : <<render>>
return Użytkownik już jest zablokowany
end


@enduml