@startuml MOK.5

actor Administrator as admin
boundary AccountPanelPage as gui
control AccountEndpoint as controller
control AccountService as service
control AccountFacade as facade
entity Account as account

admin -> gui ++ : Wygenerowanie formularza edycji użytkownika
gui -> controller ++ : addAccessLevel()
controller -> service ++ : addAccessLevel() 

alt użytkownik posiada poziom dostępu
    service -> facade ++ : addAccessLevel()
    return failure
else użytkownik nie posiada poziomu dostępu
    group Transaction.ReadCommitted
        service -> facade ++ : addAccessLevel()
        facade -> account ** : edit(account)
        return success
    end
end

return success
return HTTP 200 OK
gui -> gui : <<render>>
return Informacja o dodaniu poziomu dostępu


@enduml