@startuml MOK.5

actor Administrator as admin
boundary AccountPanelPage as gui
control AccountEndpoint as controller
control AccountService as service
control AccountFacade as facade
entity Account as account

admin -> gui ++ : Wyszukaj użytkownika
gui -> controller ++ :  findClient()
controller -> service ++ : findClient()
group Transaction.ReadOnly
    service -> facade ++ : findClient()
    return account
end
return account
return account
gui --> gui : <<render>>
return Formularz edycji użytkownika

admin -> gui ++ : Dodanie poziomu dostępu
gui -> controller ++ : addAccessLevel()
controller -> service ++ : addAccessLevel() 

group Transaction.ReadCommitted
    alt użytkownik posiada poziom dostępu
        service -> facade ++ : addAccessLevel()
        return failure
    else użytkownik nie posiada poziomu dostępu
    
        service -> facade ++ : addAccessLevel()
        facade -> account ** : edit(account)
        return success
    end
end

return success
return HTTP 200 OK
gui -> gui : <<render>>
return Informacja o dodaniu poziomu dostępu


@enduml