@startuml MOK.7 Zmiana własnego hasła

actor Użytkownik as client
boundary AccountPanelPage as gui
control AccountEndpoint as controller
control AccountService as service
control AccountFacade as facade
entity Account as account

client -> gui ++ : Wyszukaj użytkownika
gui -> controller ++ :  findUser()
controller -> service ++ : findUser()
group Transaction.ReadCommitted <<RO>>
    service -> facade ++ : findUser()
    return account
end
return account
return account
gui --> gui : <<render>>
return Formularz edycji użytkownika

client -> gui ++ : Edycja hasła
gui -> controller ++ : changePassword()
controller -> service ++ : changePassword() 
' group Transaction. ?????
' service -> service : validatePassword()
' znajdz konto

group Transaction.ReadCommitted <<RO>>
    service -> facade ++ : findUser()
    return account
end

alt niepoprawne dane
    service -> service : validatePassword()
    service --> controller : failure
    controller --> gui : Komunikat o błędzie
    gui --> client : Informacja o braku zmiany hasła
else poprawne dane
    group Transaction.ReadCommitted <<RW>>
    
        service -> service : validatePassword()
        service -> facade ++ : changePassword()
        facade -> account ** : edit(account)
    return success
    end

return success
return HTTP 200 OK
gui -> gui : <<render>>
return Informacja o zmianie hasła
end

@enduml