@startuml MOK.8

actor Administator as client
boundary AccountPanelPage as gui
control AccountEndpoint as controller
control AccountService as service
control AccountFacade as facade
entity Account as account

client -> gui ++ : Wyszukaj użytkownika
gui -> controller ++ :  findClient()
controller -> service ++ : findClient()
group Transaction.ReadOnly
    service -> facade ++ : findClient()
    return account
end
return account
return account
gui --> gui : <<render>>
return Formularz edycji użytkownika

client -> gui ++ : Edycja hasła
gui -> controller ++ : changePassword()
controller -> service ++ : changePassword() 
' group Transaction. ?????
' service -> service : validatePassword()
' znajdz konto

alt niepoprawne dane
    service -> service : validatePassword()
    service --> controller : failure
else poprawne dane
    group Transaction.ReadCommitted
        service -> service : validatePassword()
        service -> facade ++ : changePassword()
        facade -> account ** : edit(account)
    return success
    end
end

return success
return HTTP 200 OK
gui -> gui : <<render>>
return Informacja o zmianie hasła


@enduml