@startuml MOK.3 - Zablokuj konto

actor Administrator as admin
boundary AccountPanelPage as gui
control AccountEndpoint as controller
control AccountService as service
entity Account as account
control AccountFacade as facade

skinparam backgroundcolor transparent
box Transaction.Mandatory 
    participant facade
end box

admin -> gui ++ : Wywołanie wyświetlenia formularza
gui -> controller ++ : deactivateAccount(id)
group Transaction.Never
    controller -> service ++ : deactivateAccount(id) 
    group Transaction.Required
        group Transaction.ReadCommitted <<RW>>
            service -> facade ++ : findByLogin(login)
            facade --> service : result
            service -> service : <<check>>
            service -> account ** : setActive(false)
            service -> facade : edit(account)
            return success
        end
    end
end

return success
return HTTP 200 OK
gui -> gui : <<render>>
return Informacja o zablokowaniu konta

alt użytkownik jest zablokowany
    admin -> gui ++ : Wywołanie wyświetlenia formularza
    gui -> controller ++ : deactivateAccount(id)
    group Transaction.Never
        controller -> service ++ : deactivateAccount(id) 
            group Transaction.Required
                group Transaction.ReadCommitted <<RW>>
                    service -> facade ++: findByLogin(login)
                    facade --> service  : result
                    service -> service : <<check>>
                
                    return failure
                end
            end
        end
        return failure
    return HTTP 403 FORBIDDEN
    gui -> gui : <<render>>
return Użytkownik już jest zablokowany
end


@enduml