@startuml MOK.6 - Odłącz poziom dostępu

actor Administrator as admin
boundary AccountPanelPage as gui
control AccountEndpoint as controller
control AccountService as service
control AccountFacade as facade
control AccessLevelFacade as facadeLevel
entity Account as account

skinparam backgroundcolor transparent
box Transaction.Mandatory 
    participant facadeLevel
    participant facade
end box

admin -> gui ++ : Wyświetl listę użytkowników
gui -> controller ++ :  findAllAccounts()
group Transaction.Never
    controller -> service ++ : findAllAccounts()
    group Transaction.Required
        group Transaction.ReadCommitted <<RO>>
            service -> facade ++ : findAllAccounts()
            return account
        end
    end
end
return List<account>
return List<account>
gui --> gui : <<render>>
return Formularz listy użytkowników

admin -> gui ++ : Wybranie użytkownika i usunięcie poziomu dostępu
gui -> controller ++ : removeAccessLevelFromAccount()

group Transaction.Never
    controller -> service ++ : removeAccessLevelFromAccount() 

    group Transaction.ReadCommitted <<RO>>
        service -> facade ++ : findByLogin(login)
        return account
    end
end

alt użytkownik nie posiada poziom dostępu
    group Transaction.Required
        service -> facade ++ : removeAccessLevelFromAccount()
        return failure
    end
    service --> controller : failure
    controller --> gui : Komunikat o błędzie
    gui --> admin : Informacja o braku zmiany poziomów dostępu
else użytkownik posiada poziomu dostępu
    group Transaction.Required
        group Transaction.ReadCommitted <<RW>>
            service -> facade ++ : removeAccessLevelFromAccount()
            facade -> account ** : edit(account)
            service -> facadeLevel ++: remove(accessLevel)
            return success
        return success
        end
    end
return success
return HTTP 200 OK
gui -> gui : <<render>>
return Informacja o usunięciu poziomu dostępu
end

@enduml