@startuml MOK.15 - Dodaj recenzję wszczepu


actor Administrator as guest
boundary formularz_utworzenia_konta as gui
control MOKEndpoint as endpoint
entity ImplantReview as account
control MOKService as service
control ImplantReviewFacade as accFacade

skinparam backgroundcolor transparent

guest -> gui ++ : Przekazanie danych do formularza
gui -> endpoint ++ : Przekazanie danych z formularza

alt niepowodzenie walidacji danych
    endpoint --> gui : błąd walidacji
else sukces
    group Transaction.Never

        endpoint -> account **: <<create>>
        endpoint -> service ++ : .createReview(review)

        group Transaction.Required
            group Transaction.ReadCommitted <<RW>>
                box Transaction.Mandatory 
                    participant accFacade
                    alt sukces
                    service -> accFacade ++: .create(review)

                    else użytkownik już zrecenzował cyberwszczep
                        accFacade --> service : wyjątek
                    end

                    deactivate accFacade
                end box
            end
        end
        return komunikat

    end
    
    return komunikat
end

return komunikat