@startuml MOP.3 - Edytuj wszczep

actor Administrator as admin
boundary ImplantPage as gui
control MOPEndpoint as controller
control MOPService as service
entity Implant as implant
control ImplantFacade as facade

skinparam backgroundcolor transparent
box Transaction.Mandatory 
    participant facade
end box

admin -> gui ++ : Wyświetl listę wszczepów
gui -> controller ++ :  findAllImplants()
group Transaction.Never
    controller -> service ++ : findAllImplants()
    group Transaction.Required
        group Transaction.ReadCommitted <<RO>>
            service -> facade ++ : findAllImplants()
            return List<implant>
        end
    end
end
return List<implant>
return List<implant>
gui --> gui : <<render>>
return Formularz listy wszczepów

admin -> gui ++ : Wywołanie formularza edycji wszczepu
gui -> controller ++ : editImplant(id)
group Transaction.Never
    controller -> service ++: editImplant(id)
    group Transaction.Required
        group Transaction.ReadCommitted <<RW>>
            service -> facade ++ : findByName(name)
            facade -> implant : result
            service -> service : <<check>>
            service -> facade : edit(implant)
            return success
        end
    end  
end
return success
return HTTP 200 OK
gui -> gui : <<render>>
return Informacja o usunieciu wszczepu

alt Wszczep o podanej nazwie nie istnieje
admin -> gui ++ : Wywołanie formularza usuniecia implantu
gui -> controller ++ : editImplant(id)
group Transaction.Never
    controller -> service ++: editImplant(id)
    group Transaction.Required
        group Transaction.ReadCommitted <<RO>>
            service -> facade ++: findByName(name)
            facade -> implant  : result
            service -> service : <<check>>
            return failure
        end
    end
end
return failure
return HTTP 403 FORBIDDEN
gui -> gui : <<render>>
return Wszczep został już zarchiwizowany
end


@enduml