@startuml MOP.9 - Zarezerwuj wizytę

actor "Klient/Specjalista" as guest
boundary formularz_rezerwacji_wizyty as gui
control MOPEndpoint as endpoint
control MOPService as service
entity Appointment as implant
control AppointmentFacade as accFacade

skinparam backgroundcolor transparent

guest -> gui ++ : Wciśnięcie przycisku rezerwacji wizyty
gui -> endpoint ++ : Wysłanie żądania rezerwacji wizyty

group Transaction.Never

    endpoint -> service ++ : bookAppointment(appointmentId)

    group Transaction.Required
        group Transaction.ReadCommitted <<RW>>
            box Transaction.Mandatory 
                participant accFacade
                alt sukces
                service -> accFacade ++ : bookAppointment(appointmentId)
                accFacade --> service : appointment

                service -> implant ** : setStatus(REJECTED)

                service -> accFacade : bookAppointment(appointment)

                else wizyta nie istnieje
                    accFacade --> service : wyjątek
                end

                deactivate accFacade
            end box
        end
    end
    return komunikat

end

return komunikat


return komunikat

@enduml