@startuml mop_ejb_cdi_diagram
left to right direction

package pl.lodz.p.it.ssbd2022.common {
    abstract class AbstractFacade {
        -Class<T> entityClass
        +AbstractFacade(Class<T> entityClass)
        #{abstract} EntityManager getEntityManager()
        #{abstract} void HashAlgorithm getHashAlgorithm()
        +void create(T entity)
        +void edit(T entity, String eTag)
        +void unsafeEdit(T entity)
        +void remove(T entity, String eTag)
        +void unsafeRemove(T entity)
        +T find(Object id)
        +List findAll()
        +PaginationData findInRange(int pageNumber, int perPage)
        +int count()
        -void verifyTag(AbstractEntity entity, String eTag)
    }

    abstract class AbstractManager {
        #SessionContext sessionContext
        #Logger logger
        -String transactionId
        -boolean lastTransactionCommited
        +boolean isLastTransactionCommited()
        +void afterBegin()
        +void beforeCompletion()
        +void afterCompletion()
    }

    interface ManagerLocalInterface <<Interface>> {
        +boolean isLastTransactionCommited();
    }
}


package pl.lodz.p.it.ssbd2022.mop {

    ' ENDPOINTY
    package cdi.endpoints {
        interface MOPEndpointInterface <<Interface>> {
        }

        class MOPEndpoint {
                
        }           
    }

    ' FASADY
    package ejb.facades {

        class AccessLevelFacade {}

        class AccountFacade {}
        
        class ActiveAccountFacade {}

        class ResetPasswordFacade {}

    }

    ' SERWISY
    package ejb.services {

        interface MOPServiceInterface <<Interface>> {}

        class MOPService {}

    }
    
}

' extend fasad
AbstractFacade <|- AccessLevelFacade
AbstractFacade <|- AccountFacade
AbstractFacade <|- ActiveAccountFacade
AbstractFacade <|- ResetPasswordFacade

' extend/implement serwis
AbstractManager <|- mopService
ManagerLocalInterface <|- mopServiceInterface
mopServiceInterface <|- mopService

' implement endpoint
mopEndpointInterface <|- mopEndpoint

' wykorzystanie serwisu przez endpoint
mopEndpoint -> mopService

' wykorzystanie fasady przez serwis
mopService -> AccessLevelFacade
mopService -> AccountFacade
mopService -> ActiveAccountFacade
mopService -> ResetPasswordFacade


@enduml